servers:
  - url: http://localhost:8080/
    description: localhost de dev
paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags:
        - Productos
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Limitar la cantidad de resultados
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Número de página
        - in: query
          name: sort
          schema:
            type: string
            default: 'asc'
          description: Ordenar los resultados por precio ('asc' o 'desc')
        - in: query
          name: category
          schema:
            type: string
          description: Filtrar por categoría
        - in: query
          name: status
          schema:
            type: boolean
          description: Filtrar por estado de disponibilidad
      responses:
        200:
          description: Lista de productos
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: 'success'
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/product'
                  totalPages:
                    type: integer
                    example: 3
                  prevPage:
                    type: integer
                    example: null
                  nextPage:
                    type: integer
                    example: 2
                  page:
                    type: integer
                    example: 1
                  hasPrevPage:
                    type: boolean
                    example: false
                  hasNextPage:
                    type: boolean
                    example: true
                  prevLink:
                    type: string
                    example: null
                  nextLink:
                    type: string
                    example: '/api/products?page=2&limit=10&sort=asc&status=true&category=Tecnologia'
                  totalItems:
                    type: integer
                    example: 30
                  currentPage:
                    type: integer
                    example: 1
        500:
          description: Error interno del servidor

    post:
      summary: Agregar un nuevo producto
      tags:
        - Productos
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
      responses:
        201:
          description: Producto creado
        500:
          description: Error interno del servidor

  /api/products/{pid}:
    get:
      summary: Obtener un producto por ID
      tags:
        - Productos
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      responses:
        200:
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/product'
        404:
          description: Producto no encontrado
        500:
          description: Error interno del servidor

    put:
      summary: Actualizar un producto
      tags:
        - Productos
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/product'
      responses:
        200:
          description: Producto actualizado
        404:
          description: Producto no encontrado
        500:
          description: Error interno del servidor

    delete:
      summary: Eliminar un producto
      tags:
        - Productos
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      responses:
        200:
          description: Producto eliminado
        403:
          description: No tiene permiso para eliminar este producto
        404:
          description: Producto no encontrado
        500:
          description: Error interno del servidor
components:
  schemas:
    product:
      type: object
      properties:
        title:
          type: string
          description: The title of the product
          example: 'Smartphone'
        description:
          type: string
          description: A short description of the product
          example: 'Latest model with advanced features'
        price:
          type: number
          description: The price of the product
          example: 999.99
        thumbnails:
          type: string
          description: A URL to a thumbnail image of the product
          example: 'http://example.com/thumbnail.jpg'
        code:
          type: string
          description: A unique code for the product
          example: 'SP123'
        stock:
          type: string
          description: The number of items in stock
          example: '500'
        status:
          type: boolean
          description: The availability status of the product
          example: true
        category:
          type: string
          description: The category of the product
          enum:
            - Hogar
            - Tecnologia
            - Cocina
            - Higiene
          example: 'Tecnologia'
        owner:
          type: string
          description: The owner of the product
          example: 'admin'